

services:
  bev:
    build:
      context: ./BEV-API
      dockerfile: Dockerfile
    container_name: bev
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - shared_data:/shared_data

  ttc:
    build:
      context: ./TTC-API
      dockerfile: Dockerfile
    container_name: ttc
    ports:
      - "8001:8001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - shared_data:/shared_data

volumes:
  shared_data:
